### ISSUE TITLE
Error occurs when importing to the blender

### ISSUE THREAD

**Issue by Renata-Yun** [FlazeIGuess/TinyGlade-Blender-AddOn#1]
I try to use your "tiny_glade_json_io.py", but when I import object (.json file of Tine Glade), I get error:
line 32, in execute: vertices = [Vector(v) for v in data['Vertex_Position']['buffer']]
KeyError: 'Vertex_Position'

![Снимок экрана_20241023_140735](https://github.com/user-attachments/assets/927512b0-f15c-4ae4-bb68-c21d3901f534)

Maybe I'm doing something wrong((

**Comment by FlazeIGuess** [comment]
What are you trying to import? You have to import the meshes, look at my tutorial:)

**Comment by Renata-Yun** [comment]
> What are you trying to import? You have to import the meshes, look at my tutorial:)

After watching the tutorial, I figured out how to work with this. Thanks!))

And, do you know if it is possible to import the created world of Tiny Glade into a Blender??

**Comment by FlazeIGuess** [comment]
> > What are you trying to import? You have to import the meshes, look at my tutorial:)
> 
> After watching the tutorial, I figured out how to work with this. Thanks!))
> 
> And, do you know if it is possible to import the created world of Tiny Glade into a Blender??

Actually idk, you could try that :)
